In [37]:
import pandas as pd
from pathlib import Path

In [ ]:
# from the file: analisi_20241217_miRNAs_OPCs_Bowtie1_v_0_m_1_mismatch_align
# and the part: DEGs_FDR_5pc_NO_FC

In [38]:
path1 = Path("/Users/zainabnazari/mfuzz/data")

In [15]:
data_miRNA2_6 = pd.read_excel(path1/"miRNA_DE_2_6.xlsx")

In [16]:
data_miRNA2_6.columns

Index(['Unnamed: 0', 'sequence', 'baseMean', 'log2FoldChange', 'lfcSE', 'stat',
       'pvalue', 'padj'],
      dtype='object')

In [17]:
data_miRNA2_6.rename(columns={'Unnamed: 0': 'miRNA_ID'}, inplace=True)

In [18]:
data_miRNA2_6

,miRNA_ID,sequence,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,mmu-let-7a-2-3p,CTGTACAGCCTCCTAGCTTTC,4.685052,5.378144,2.051730,2.621273,0.008760,0.084812
1,mmu-let-7a-5p,TGAGGTAGTAGGTTGTATAGTT,110787.030607,-0.045986,0.174978,-0.262812,0.792695,0.933749
2,mmu-let-7b-3p,CTATACAACCTACTGCCTTCCC,245.932230,0.097525,0.247922,0.393368,0.694048,0.890682
3,mmu-let-7b-5p,TGAGGTAGTAGGTTGTGTGGTT,24643.673730,0.046311,0.149041,0.310730,0.756006,0.917367
4,mmu-let-7c-1-3p,CTGTACAACCTTCTAGCTTTCC,50.189086,-0.040092,0.613953,-0.065302,0.947934,0.992075
...,...,...,...,...,...,...,...,...
1251,mmu-miR-99a-3p,CAAGCTCGTTTCTATGGGTCT,42.306369,-0.189732,0.645491,-0.293934,0.768808,0.919448
1252,mmu-miR-99a-5p,AACCCGTAGATCCGATCTTGTG,457606.255932,-0.481329,0.244286,-1.970352,0.048798,0.211134
1253,mmu-miR-99b-3p,CAAGCTCGTGTCTGTGGGTCCG,109.785362,-0.478732,0.344299,-1.390457,0.164390,0.425290
1254,mmu-miR-99b-5p,CACCCGTAGAACCGACCTTGCG,33056.278695,-0.752770,0.161517,-4.660623,0.000003,0.000207
1255,mmu-miR-9b-5p,TTCGGTTATCTAGCTTTATGA,2.694465,-0.606422,1.827004,-0.331922,0.739948,0.911638

In [19]:
# Check for duplicates in the 'miRNA_ID' column
duplicates = data_miRNA2_6[data_miRNA2_6['miRNA_ID'].duplicated(keep=(False))]

# Print the duplicates
duplicates

Empty DataFrame
Columns: [miRNA_ID, sequence, baseMean, log2FoldChange, lfcSE, stat, pvalue, padj]
Index: []

# Second file 6-12 Months

In [20]:
data_miRNA6_12 = pd.read_excel(path1/"miRNA-6M_12M.xlsx")

In [21]:
data_miRNA6_12

,Unnamed: 0,sequence,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,mmu-miR-1264-3p,CAAATCTTATTTGAGCACCTGT,14997.868751,-2.553652,0.367496,-6.948786,3.684442e-12,1.484830e-09
1,mmu-miR-1298-5p,TTCATTCGGCTGTCCAGATGTA,16975.985098,-2.108564,0.344318,-6.123887,9.131943e-10,1.226724e-07
2,mmu-miR-5099,TTAGATCGATGTGGTGCTCC,71.879288,-2.086749,0.500870,-4.166246,3.096571e-05,6.623148e-04
3,mmu-miR-448-3p,TTGCATATGTAGGATGTCCCAT,2293.849997,-1.881322,0.290709,-6.471497,9.703652e-11,1.955286e-08
4,mmu-miR-20a-3p,ACTGCATTACGAGCACTTAAAG,116.166191,-1.780963,0.584516,-3.046901,2.312136e-03,1.901614e-02
...,...,...,...,...,...,...,...,...
79,mmu-miR-874-3p,CTGCCCTGGCCCGAGGGACCGA,754.812407,0.902743,0.252306,3.577972,3.462701e-04,4.983816e-03
80,mmu-miR-491-5p,AGTGGGGAACCCTTCCATGAGG,108.902138,0.972796,0.365200,2.663737,7.727802e-03,4.208519e-02
81,mmu-miR-92b-5p,AGGGACGGGACGTGGTGCAGTGTT,165.425855,1.032048,0.361379,2.855861,4.292034e-03,2.745539e-02
82,mmu-miR-770-5p,AGCACCACGTGTCTGGGCCACG,445.481180,1.138875,0.398091,2.860843,4.225164e-03,2.745539e-02
83,mmu-miR-323-5p,AGGTGGTCCGTGGCGCGTTCGC,160.345824,1.532001,0.526154,2.911700,3.594680e-03,2.534370e-02

In [22]:
data_miRNA6_12.rename(columns={'Unnamed: 0': 'miRNA_ID'}, inplace=True)

In [23]:
data_miRNA6_12

,miRNA_ID,sequence,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,mmu-miR-1264-3p,CAAATCTTATTTGAGCACCTGT,14997.868751,-2.553652,0.367496,-6.948786,3.684442e-12,1.484830e-09
1,mmu-miR-1298-5p,TTCATTCGGCTGTCCAGATGTA,16975.985098,-2.108564,0.344318,-6.123887,9.131943e-10,1.226724e-07
2,mmu-miR-5099,TTAGATCGATGTGGTGCTCC,71.879288,-2.086749,0.500870,-4.166246,3.096571e-05,6.623148e-04
3,mmu-miR-448-3p,TTGCATATGTAGGATGTCCCAT,2293.849997,-1.881322,0.290709,-6.471497,9.703652e-11,1.955286e-08
4,mmu-miR-20a-3p,ACTGCATTACGAGCACTTAAAG,116.166191,-1.780963,0.584516,-3.046901,2.312136e-03,1.901614e-02
...,...,...,...,...,...,...,...,...
79,mmu-miR-874-3p,CTGCCCTGGCCCGAGGGACCGA,754.812407,0.902743,0.252306,3.577972,3.462701e-04,4.983816e-03
80,mmu-miR-491-5p,AGTGGGGAACCCTTCCATGAGG,108.902138,0.972796,0.365200,2.663737,7.727802e-03,4.208519e-02
81,mmu-miR-92b-5p,AGGGACGGGACGTGGTGCAGTGTT,165.425855,1.032048,0.361379,2.855861,4.292034e-03,2.745539e-02
82,mmu-miR-770-5p,AGCACCACGTGTCTGGGCCACG,445.481180,1.138875,0.398091,2.860843,4.225164e-03,2.745539e-02
83,mmu-miR-323-5p,AGGTGGTCCGTGGCGCGTTCGC,160.345824,1.532001,0.526154,2.911700,3.594680e-03,2.534370e-02

In [24]:
# Check for duplicates in the 'miRNA_ID' column
duplicates = data_miRNA6_12[data_miRNA6_12['miRNA_ID'].duplicated(keep=(False))]

# Print the duplicates
duplicates

Empty DataFrame
Columns: [miRNA_ID, sequence, baseMean, log2FoldChange, lfcSE, stat, pvalue, padj]
Index: []

# Now we have two files ready
data_miRNA6_12, data_miRNA2_6

In [40]:
# renaming the columns 
fileA = data_miRNA2_6.rename(columns={'log2FoldChange': 'FC_2_6' })
fileB = data_miRNA6_12.rename(columns={'log2FoldChange': 'FC_6_12'})

In [41]:
fileA

,miRNA_ID,sequence,baseMean,FC_2_6,lfcSE,stat,pvalue,padj
0,mmu-let-7a-2-3p,CTGTACAGCCTCCTAGCTTTC,4.685052,5.378144,2.051730,2.621273,0.008760,0.084812
1,mmu-let-7a-5p,TGAGGTAGTAGGTTGTATAGTT,110787.030607,-0.045986,0.174978,-0.262812,0.792695,0.933749
2,mmu-let-7b-3p,CTATACAACCTACTGCCTTCCC,245.932230,0.097525,0.247922,0.393368,0.694048,0.890682
3,mmu-let-7b-5p,TGAGGTAGTAGGTTGTGTGGTT,24643.673730,0.046311,0.149041,0.310730,0.756006,0.917367
4,mmu-let-7c-1-3p,CTGTACAACCTTCTAGCTTTCC,50.189086,-0.040092,0.613953,-0.065302,0.947934,0.992075
...,...,...,...,...,...,...,...,...
1251,mmu-miR-99a-3p,CAAGCTCGTTTCTATGGGTCT,42.306369,-0.189732,0.645491,-0.293934,0.768808,0.919448
1252,mmu-miR-99a-5p,AACCCGTAGATCCGATCTTGTG,457606.255932,-0.481329,0.244286,-1.970352,0.048798,0.211134
1253,mmu-miR-99b-3p,CAAGCTCGTGTCTGTGGGTCCG,109.785362,-0.478732,0.344299,-1.390457,0.164390,0.425290
1254,mmu-miR-99b-5p,CACCCGTAGAACCGACCTTGCG,33056.278695,-0.752770,0.161517,-4.660623,0.000003,0.000207
1255,mmu-miR-9b-5p,TTCGGTTATCTAGCTTTATGA,2.694465,-0.606422,1.827004,-0.331922,0.739948,0.911638

In [42]:
merged_df = pd.merge(fileA[['miRNA_ID','baseMean', 'FC_2_6']], fileB[['miRNA_ID', 'FC_6_12']], on='miRNA_ID')

In [45]:
merged_df

          miRNA_ID       baseMean    FC_2_6   FC_6_12
0    mmu-let-7a-5p  110787.030607 -0.045986  0.761791
1    mmu-let-7c-5p  130175.671522 -0.027348  0.823213
2    mmu-let-7d-3p    2312.332906 -0.032037 -0.592754
3    mmu-let-7d-5p   78718.562642  0.061417  0.577850
4    mmu-let-7e-5p   30012.253872  0.206413  0.717728
..             ...            ...       ...       ...
79  mmu-miR-874-3p     754.812407  0.591251  0.902743
80  mmu-miR-92b-5p     165.425855 -0.538302  1.032048
81   mmu-miR-93-5p    1970.372303  0.045091  0.467843
82   mmu-miR-98-5p    4397.370544 -0.260280  0.413255
83  mmu-miR-99a-5p  457606.255932 -0.481329 -1.159393

[84 rows x 4 columns]

In [46]:
merged_df.to_excel(path1/"merged_mixed_miRNA.xlsx", index=False)